name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build customer-service image
      run: docker build ./customer-service -t customer-service

    - name: Build order-service image
      run: docker build ./order-service -t order-service

    - name: Build restaurant-service image
      run: docker build ./restaurant-service -t restaurant-service
